name: Iflaunta CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  health-check-test:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: True

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Syntax and Code Formatting
      run: pycodestyle --select=E1,E9 --statistics .
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Tests
      run: python manage.py test
